env: multigrid-lbf-extended-v0

env_args:
    # size of the area accessible by the agents
    map_name: ""
    width: 10
    height: 10
    n_agents: 4
    max_num_fruit: 2
    force_coop: False
    sight: 2
    max_episode_steps: 50

    state_type: original
    obs_type: original

    # only works for multigrid obs
    highlight_visible_cells: False

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 2050000
test_interval: 10000
test_nepisode: 40
